### ISSUE TITLE
Valores divergentes entre gráfico de acessos e arquivo CSV

### ISSUE THREAD

**Issue by ednilson** [scieloorg/analytics#116]
O gráfico de acesso no analytics (acessos em  2015) apresenta valores diferentes daqueles fornecidos no arquivo CSV  "access_by_journals.csv". Isso ocorre para muitos periódicos quando se analisa os acessos no ano de 2015.

Exemplo: Memórias do Instituto Oswaldo Cruz
https://analytics.scielo.org/w/accesses?journal=0074-0276&collection=scl

Dados baixados de https://analytics.scielo.org/w/reports
Brasil - link:  https://static.scielo.org/tabs/tabs_bra.zip
arquivo: "access_by_journals.csv"

title at SciELO | publishing year | accesses year | total accesses
-- | -- | -- | --
Memórias do Instituto Oswaldo Cruz | 2011 | 2015 | 158926
Memórias do Instituto Oswaldo Cruz | 2012 | 2015 | 100547
Memórias do Instituto Oswaldo Cruz | 2013 | 2015 | 85459
Memórias do Instituto Oswaldo Cruz | 2014 | 2015 | 74295
Memórias do Instituto Oswaldo Cruz | 2015 | 2015 | 71276

Valores fornecidos pelo grafico de Acesso no ano de 2015 (tabela exportada do gráfico): 

Publishing year | 2015 | DateTime | Navigator 1
-- | -- | -- | --
2011-01-01 00:00:00 | 125246 | 2011-01-01 00:00:00 | 125246
2012-01-01 00:00:00 | 79478 | 2012-01-01 00:00:00 | 79478
2013-01-01 00:00:00 | 64527 | 2013-01-01 00:00:00 | 64527
2014-01-01 00:00:00 | 52014 | 2014-01-01 00:00:00 | 52014
2015-01-01 00:00:00 | 67965 | 2015-01-01 00:00:00 | 67965

![image](https://user-images.githubusercontent.com/454847/37768950-2e843426-2dae-11e8-88c1-3269f806f0c3.png)

**Comment by fabiobatalha** [comment]
Olá @ednilson 

Os dados estao corretos. A interface do Analytics tem diversos filtros aplicados aos resultados dos gráficos, um deles é o filtro de período dos acessos a ser considerado.

Por default a aplicaçao utiliza os últimos 3 anos a partir da data atual.

![screenshot from 2018-03-22 09-29-57](https://user-images.githubusercontent.com/504142/37773445-04d91c76-2db4-11e8-9f4b-6da61f231611.png)

Isso significa que se você nao ajustar esse período para consideral todo o ano de 2015, os valores de acessos para 2015 nao irao considerar os acessos de 1 de janeiro a 22 de março.

Você pode clicar no botao ALL e consultar novamente os dados de acessos em 2015.

publishing year | 2015 | 
-- | -- |
2011-01-01 00:00:00 | 158926
2012-01-01 00:00:00 | 100547
2013-01-01 00:00:00 | 85459
2014-01-01 00:00:00 | 74295
2015-01-01 00:00:00 | 71276

**Comment by ednilson** [comment]
@fabiobatalha Entendi.
Desconsidere esse issue.
