### ISSUE TITLE
mistakes in a paper

### ISSUE THREAD

**Issue by davidfmaulen** [scieloorg/analytics#130]
I, mi name is David Maulen, i read my article here but, it'doesn't have my affiliation dmaulen@utem.cl,  UTEM Architecture School, Chile, and my name is David Maulen, not Mauelen.

http://scielo.senescyt.gob.ec/scielo.php?script=sci_arttext&pid=S2477-91992018000200060

Please i need you change it in the right way

Really thank you from Chile, 

David Maulen

**Comment by ednilson** [comment]
Dear David,

Please contact the SciELO Ecuador technical team to correct these errors.

http://scielo.senescyt.gob.ec/equipe/equipe_e.htm
