### ISSUE TITLE
Relatório documents_dates.csv com datas incompletas e incorretas

### ISSUE THREAD

**Issue by ednilson** [scieloorg/analytics#138]
### Descrição do problema
Relatório 'documents_dates.csv' com datas incompletas e incorretas.

### Passos para reproduzir o problema
1. Acesse a página https://analytics.scielo.org/w/reports
2. Clique no link **file name: tabs_bra.zip** e baixe o arquivo tabs_bra.zip
3. Descompacte o arquivo documents_dates.csv
4. Impotar o CSV acima em qualquer ferramenta de análise de dados e analisar documentos de publicados em 2019 ou 2020.
5. Exemplo: localizar o PID S1806-11172019000100401 e observer as seguintes colunas:
'document published at'  = 2019 (data incompleta)
'document published in SciELO at' = 7/16/2018 (suposto erro - data inferior a data de publicação)

### Comportamento esperado
Que as colunas 'document published at' e 'document published in SciELO at' sejam preenchidas com as datacorretas.

**Comment by robertatakenaka** [comment]
@ednilson 
A data usada para preencher `document published at`
https://github.com/scieloorg/xylose/blob/8488a5dcf22e90816e9ec5d4ce02fb61777f462b/xylose/scielodocument.py#L1836 está "_deprecated_", deve-se usar `document_publication_date` ou `issue_publication_date` no lugar. Qual seria? Seria `issue_publication_date`, pois é a data editorial (do fascículo)?

E em `document published in SciELO at` seria a data `document_publication_date` no lugar de `creation_date`, suponho.

**Comment by ednilson** [comment]
@robertatakenaka 
Para preencher `document published at` acho que devemos usar `document_publication_date`. Tenho como base também isto:
https://github.com/scieloorg/xylose/blob/8488a5dcf22e90816e9ec5d4ce02fb61777f462b/xylose/scielodocument.py#L1857

E para preencher `document published in SciELO at` eu manteria então o `creation_date`, independente
se a data do documento for anterior ou posterior a sua publicação no site SciELO. Um dos objetivos é medir o **tempo em meses** entre a data original do documento até a sua publicação no portal SciELO.

Na "Descrição do problema", talvez eu não tenha sido muito claro, mas quis me refir à informação entrege nos relatórios CSV. Aponto para a forma como o relatório está sendo gerado. Neste caso, talvez haja a necessidade de atualizar o xylose no módulo processing, o qual provê os relatórios do Analytics.
https://github.com/scieloorg/processing/blob/master/requirements.txt#L5
