### ISSUE TITLE
Relatório documents_affiliations.csv com instituições incorretas

### ISSUE THREAD

**Issue by ednilson** [scieloorg/analytics#139]
### Descrição do problema
Relatório 'documents_affiliations.csv' com instituições incorretas. (Gerado pelo [processing](https://github.com/scieloorg/processing/blob/138389b9d44df92daddeb1107fd78ae7849c0b66/publication/documents_affiliations.py#L133), que usa os dados do article meta)

### Passos para reproduzir o problema
1. Acesse a página https://analytics.scielo.org/w/reports
2. Clique no link **file name: tabs_bra.zip** e baixe o arquivo tabs_bra.zip
3. Descompacte o arquivo documents_affiliations.csv
4. Impotar o CSV acima em qualquer ferramenta de análise de dados e analisar a instituição do PID S0370-44672014000300009
5. Exemplo: localizar o PID S0370-44672014000300009 e observer a coluna:
'document affiliation instituition' = Universidade de São Paulo
6. Observar o artigo com afiliação correta: "Universidade Federal de Ouro Preto"
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0370-44672014000300009
7. Observar a presença de erros no Aticlemeta (suspeita de erro no momento da carga dos dados)
http://articlemeta.scielo.org/api/v1/article/?code=S0370-44672014000300009 
8. Caso o módulo gerador de relatórios utilize a biblioteca Xylose, verificar a versão e o comportamento dos métodos 'affiliations', 'authors' e 'mixed_affiliations'

### Comportamento esperado
Que a coluna 'document affiliation instituition' seja preenchida com o dado de acordo com o artigo original. 
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0370-44672014000300009

**Comment by robertatakenaka** [comment]
O problema é que o campo v240, que deveria conter os dados normalizados da afiliação, está com os dados incorretos.
<img width="386" alt="Captura de Tela 2020-02-04 às 10 04 41" src="https://user-images.githubusercontent.com/505143/73747318-f657a800-4735-11ea-9861-f0ce98def2c0.png">
<img width="389" alt="Captura de Tela 2020-02-04 às 10 04 33" src="https://user-images.githubusercontent.com/505143/73747337-ff487980-4735-11ea-9830-a0478314f15d.png">
<img width="600" alt="Captura de Tela 2020-02-04 às 10 01 03" src="https://user-images.githubusercontent.com/505143/73747341-040d2d80-4736-11ea-97a6-fea6e123301d.png">

A solução é ignorar este campo para todos os registros, concordam @gustavofonseca @ednilson ?
Aparentemente foi inserido com aquelas inicitivas de padronizar os nomes das instituições, pois este dado não consta na base ISIS.

**Comment by ednilson** [comment]
Verifiquei no registro da base artigo (ISIS) e conclui que não há campo v240 preenchido (e isso está correto).
Observar de onde ou como esses dados foram incluídos no articlemeta.

ISIS output:

`mx artigo "HR=S0370-44672014000300009" 
       1  HR=S0370-44672014000300009
       1  Set #000000001
Hits=1
mfn=6874400 
  4  "v67n3"
702  "V:\SciELO\serial\rem\v67n3\markup\a09v67n3.htm"
705  "S"
706  "h"
700  "2"
701  "1"
709  "article"`

**Comment by ednilson** [comment]
@robertatakenaka sim ... acabei de verificar o registro no ISIS e não consta v240. Eu desconheço a iniciativa passada de padronizar inserindo no articlemeta.

**Comment by ednilson** [comment]
Extraindo informações de afiliações com Xylose (release 1.33.1) - observer o método **mixed_affiliations**. Talvez isso demande alguma correção no Xylose?

In [1]: import requests                                                                                                                                                        

In [2]: from xylose.scielodocument import Article                                                                                                                              

In [3]: r = requests.get("http://articlemeta.scielo.org/api/v1/article/?code=S0370-44672014000300009")                                                                         

In [4]: doc = Article(r.json())                                                                                                                                                

In [5]: **doc.affiliations**                                                                                                                                                       
Out[5]: 
[{'institution': 'PPGEM',
  'index': 'A01',
  'orgdiv1': 'UFOP',
  'orgdiv2': 'Departamento de Mineração'},
 {'institution': 'PPGEM',
  'index': 'A02',
  'city': 'Ouro Preto',
  'state': 'Minas Gerais',
  'country': 'Brasil',
  'country_iso_3166': 'BR',
  'email': 'valdir@demin.ufop.br',
  'orgdiv1': 'DEMIN',
  'orgdiv2': 'UFOP'},
 {'institution': 'PPGEM',
  'index': 'A03',
  'city': 'Ouro Preto',
  'state': 'Minas Gerais',
  'country': 'Brasil',
  'country_iso_3166': 'BR',
  'email': 'hernani.lima@ufop.br',
  'orgdiv1': 'DEMIN',
  'orgdiv2': 'UFOP'}]

In [6]: **doc.mixed_affiliations**                                                                                                                                                 
Out[6]: 
[{'institution': 'Universidade de São Paulo',
  'index': 'A01',
  'orgdiv1': 'UFOP',
  'orgdiv2': 'Departamento de Mineração',
  'normalized': True,
  'country_iso_3166': 'BR',
  'country': 'Brazil',
  'state': 'São Paulo'},
 {'institution': 'Universidade de São Paulo',
  'index': 'A02',
  'city': 'Ouro Preto',
  'state': 'São Paulo',
  'country': 'Brazil',
  'country_iso_3166': 'BR',
  'email': 'valdir@demin.ufop.br',
  'orgdiv1': 'DEMIN',
  'orgdiv2': 'UFOP',
  'normalized': True},
 {'institution': 'Universidade de São Paulo',
  'index': 'A03',
  'city': 'Ouro Preto',
  'state': 'São Paulo',
  'country': 'Brazil',
  'country_iso_3166': 'BR',
  'email': 'hernani.lima@ufop.br',
  'orgdiv1': 'DEMIN',
  'orgdiv2': 'UFOP',
  'normalized': True}]

**Comment by robertatakenaka** [comment]
@ednilson eu já diagnostiquei que os dados estão incorretos. A questão é se eleminamos os campos que contém os dados normalizados para todos os registros ou se eleminamos apenas para aqueles que conseguimos identificar que estão incorretos como este que no v70 o estado é Minas Gerais e no v240 é São Paulo.

**Comment by robertatakenaka** [comment]
Em [](https://github.com/scieloorg/xylose/blob/8488a5dcf22e90816e9ec5d4ce02fb61777f462b/xylose/scielodocument.py#L2381) 
Há: 
```python
    @property
    def mixed_affiliations(self):
        """
        This method retrieves the normalized affiliations of the given
        article, if it exists.
        If some document does not have all the affiliations normalized, this
        method will mix the original affiliation data with the normalized data.
        """
        normalized = {}

        if self.affiliations:
            for aff in self.affiliations:
                    normalized[aff['index']] = aff.copy()
                    normalized[aff['index']]['normalized'] = False
                    normalized[aff['index']]['country_iso_3166'] = aff.get('country_iso_3166', '')

        if self.normalized_affiliations:
            for aff in self.normalized_affiliations:
                if not aff['index'] in normalized:
                    continue
                normalized[aff['index']]['normalized'] = True
                normalized[aff['index']]['country'] = aff.get('country', '')
                normalized[aff['index']]['country_iso_3166'] = aff.get('country_iso_3166', '')
                normalized[aff['index']]['institution'] = aff.get('institution', '')
                normalized[aff['index']]['state'] = aff.get('state', '')

        return [v for i, v in normalized.items()]
```

```python
    @property
    def normalized_affiliations(self):
        """
        This method retrieves the affiliations of the given article, if it exists.
        This method deals with the legacy fields (240).
        """
        affiliations = []
        if 'v240' in self.data['article']:
            for aff in self.data['article']['v240']:
                affdict = {}
                if '_' in aff:
                    if len(aff['_'].strip()) > 0:
                        affdict['institution'] = html_decode(aff['_'])

                        if 'i' in aff:
                            affdict['index'] = aff['i'].upper()
                        else:
                            affdict['index'] = ''

                        if 'p' in aff and html_decode(aff['p']).lower() in iso3166.COUNTRY_CODES_ALPHA_2_FORMS:
                            affdict['country_iso_3166'] = iso3166.COUNTRY_CODES_ALPHA_2_FORMS.get(aff['p'].lower(), '')
                            affdict['country'] = html_decode(iso3166.COUNTRY_CODES_ALPHA_2.get(aff['p'], {'name': html_decode(aff['p'])})['name'])

                        if 's' in aff:
                            affdict['state'] = aff['s']

                        affiliations.append(affdict)

        if len(affiliations) == 0:
            return None

        return affiliations
```

Minha sugestão é tentar avaliar se v240 é válido ou não. Se sim, usá-lo em `mixed_affiliations` caso contrário, não.
Minha sugestão é mudar o nome `normalized_affiliations` para `raw_normalized_affiliations`.
O `normalized_affiliations` teria apenas o `normalized_affiliations` que tenha sido possível validar, ou seja, de identificar que é uma normalização da correspondente v70.

**Comment by ednilson** [comment]
@robertatakenaka e demais... concordo em mudar para o `raw_normalized_affiliations` e manter o `normalized_affiliations` somente para aqueles que foram validados.
Tem que validar também os impactos dessa mudança.

**Comment by robertatakenaka** [comment]
@ednilson certamente vai modificar o relatório, no entanto, acredito num impacto positivo já que não mostrará dados errados. Obviamente isso não é 100% garantido, pois pode eliminar o v240 de dados que estão corretos por não ser possível algum `match`.
É possível simular isso antes de fazer o PR.

**Comment by robertatakenaka** [comment]
@ednilson @gustavofonseca @jamilatta @patymori @joffilyfe 

https://drive.google.com/open?id=1T6nQ1v_JToVagKg-vjxiR-GrupQIAs9G

No arquivo:

- original.csv - são os dados originais da afiliação
- merged_common.csv - são os dados que são originais + atualizados com os dados normalizados

- merged_old.csv - na lógica antiga, os dados originais eram sobrescritos como os dados normalizados
- merged_new.csv - na lógica nova, os dados originais **só** são sobrescritos como os dados normalizados, caso não haja conflitos. Por conflitos, entendemos que os originais e os normalizados tem dados divergentes, por exemplo, estado: MG e SP.

Em conflitos.log lista estes conflitos.

**Comment by robertatakenaka** [comment]
A correção foi feita no xylose (1.35.8). Usam xylose em 19 repositórios. Esta mudança impacta em:

- article meta (1.45.8)
- processing
