### ISSUE TITLE
[Analytics] Considerar nas métricas o tipo de documento data-article como citável

### ISSUE THREAD

**Issue by ednilson** [scieloorg/analytics#143]
### Descrição da tarefa
Considerar nas métricas o tipo de documento data-article como citável.
Este issue atende parte da resolução de outro issue em scielorg: https://github.com/scieloorg/articles_meta/issues/183

### Subtarefas

- [x] Verificar Controller
https://github.com/scieloorg/analytics/blob/master/analytics/controller.py#L21
- [x] Verificar as traduções de mensagens da aplicação e gráficos
Gráfico:
https://analytics.scielo.org/w/publication/article_by_publication_year#received-granted-and-self-citing
Código:
https://github.com/scieloorg/analytics/blob/master/analytics/locale/analytics.pot#L761

## Considerações e notas

* Rastrear o código para verificar se há outros impactos baseados nesta tarefa.

**Comment by gustavofonseca** [comment]
Movi este ticket para a coluna _Iniciado_ por não se tratar de um _pull request_.
