### ISSUE TITLE
Incluir marca d'agua SciELO nos gráficos.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/analytics#22]

**Comment by swarzesherz** [comment]
La inclusión de marca de agua tendrá que ser en el fondo de la gráfica, ya que highcharts no permite agregar una imagen de fondo, el problema de esto es que al exportar la imagen esta no tendrá la marca de agua.
Podría solucionarse con http://html2canvas.hertzen.com, pero tiene algunos problemas con el render de svg, porque que también hay que transformar la gráfica a imagen https://github.com/gabelerner/canvg

**Comment by fabiobatalha** [comment]
Creo que se puede poner el logo en la fuente.

**Comment by fabiobatalha** [comment]
sin marca d'agua
