### ISSUE TITLE
Incluir controle de período de ano de publicação

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/analytics#40]
Para gráficos que possuem o ano de publicação no eixo X, incluir um controle para definir o período de 
interesse.

Exemplo de gráfico que deve ter o controle de período de ano de publicação.

![chart](https://cloud.githubusercontent.com/assets/504142/12196872/57ba8e88-b5e9-11e5-8273-5bd3d9fcb585.jpeg)

Para isso é possível utlizar o ZoomType, entretanto, por ser uma funcionalidade implicita, é necessário incluir um label indicado a existência da funcionalidade, como por exemplo: Clique e arraste para selecionar um período.

Também pode ser avaliado o uso do RangeSelector.

**Comment by swarzesherz** [comment]
Me parece que es mejor utilizar "RangeSelector", que en realidad es cambiar la biblioteca de highcharts por highstock, que es donde esta esa funcionalidad, hice algunas pruebas y las demás gráficas al parecer funcionan correctamente
![screen shot 2016-01-08 at 8 57 04](https://cloud.githubusercontent.com/assets/197827/12200709/0d3bfdc2-b5e6-11e5-972a-8fd3eaad7674.png)
Creo que es mejor mostrar el control de selección de rango, a mostrar solo un label

**Comment by fabiobatalha** [comment]
Perfecto lo haremos

**Comment by swarzesherz** [comment]
Solo falta el merge del PR de ayer y realizo los cambios sobre eso...

**Comment by fabiobatalha** [comment]
Yo lo hago acá!

**Comment by fabiobatalha** [comment]
Hecho el merge.

**Comment by fabiobatalha** [comment]
Sacando la libreria highcharts la parte de exportación para PNG, JPEG, XSL, CSV no funciona. Creo que el mejor es compilar el JS para contener todas las dependencias utilizando el Download Builder.

http://www.highcharts.com/download
