### ISSUE TITLE
Ajustar regra de identificação de documentos citáveis.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/analytics#69]
De acordo com pedido da coordenação científica do SciELO, os tipos de documentos que devem ser considerados como citáveis são:

article-commentary
brief-report
case-report
rapid-communication
research-article
review-article

Os demais tipos de documentos presentes no SciELO Publishing Schema são considerados não citáveis:

abstract
book-review
correction
editorial
letter
news
press-release
undefined

**Comment by abelpacker** [comment]
Fabio, Correto. Considerando os dados de 10 de abril a distribuição é a seguinte:
![image](https://cloud.githubusercontent.com/assets/6594283/14906988/c5a93410-0d98-11e6-8d7c-459319ba2c5f.png)

total de artigos:21702
citáveis:19581
não citáveis: 1314
indefinidos:  381

Abc. Abel
