### ISSUE TITLE
Problemas com o valor (0 ou 1) para áreas temáticas.

### ISSUE THREAD

**Issue by ednilson** [scieloorg/analytics#72]
Dos arquivos journals*.csv disponíveis em Downloads - http://analytics.scielo.org/w/downloads - as que possuem as colunas 'title is exact and earth science' e 'title is literature and arts' são geradas com valor 0 (zero) para todas as revistas. 

Isto foi verificado nas coleções Brasil e Chile, mas provavelmente ocorre para todas as coleções.

**Comment by fabiobatalha** [comment]
Corrigido no projeto processing.
