### ISSUE TITLE
Verificar a atualização de CSVs  (downloads)

### ISSUE THREAD

**Issue by ednilson** [scieloorg/analytics#82]
@fabiobatalha 
Detectamos que o arquivo journals.csv do pacote de downloads SciELO Brasil não atualizou a coluna "date of the last document", "volume of the last document" e "issue of the last document".

Veja exemplo da **Brazilian Journal of Pharmaceutical Sciences**, que indica data do último documento em  2015-09(v51n3) sendo que no site já constam mais 2 fascículos, sendo o último datado de jan/mar.2016.

http://www.scielo.br/scielo.php?script=sci_issues&pid=1984-8250&lng=en&nrm=iso

**Comment by fabiobatalha** [comment]
@ednilson 

Avaliando os resultando produzidos no dia 10 de agosto, as tabulações estão corretas e apresentando o último fascículo incluído na base de dados.

Vale lembrar que os dados apresentados representam o corpus de documentos processados pelo SciELO até o momento da produção das tabulações, e que existe um período de 30 dias entre a atualização de uma tabulação para outra.

As tabulações são produzidas todo dia 10 de cada mês.

Nenhum problema foi detectado nos processamentos.
