### ISSUE TITLE
Incluir opção "Todas" no filtro de "Coleções"

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/analytics#92]
Atualmente quando entramos no Analytics já vem "Brasil" no relatório estatístico, porém não achei uma opção "todas" para que eu possa ver qual o número total de periódicos da rede. Lá no menu "Coleções" poderia ser incluído mais um item "todas". 
Essa questão surgiu porque eu queria saber qual o número geral de periódicos da rede. No site http://www.scielo.org/php/index.php diz que o número é "1,249  Journals". No CSV http://static.scielo.org/sps/titles-tab-utf-8.csv possui "1614 registros". E no Analytics eu não soube achar essa informação. Afinal, qual está certo?

**Comment by fabiobatalha** [comment]
O Analytics não foi projetado para atender a visualização do todo.

A visualização do todo tem complicações diversas no SciELO, dado que uma revista, artigo, etc pode fazer parte de mais de uma coleção. Essas complicações aumentam extremamente a complexidade de produção de indicadores pois é necessário na visão do todo realizar a exclusão de itens duplicados.

A gestão descentralizada de metadados do SciELO (coleções temáticas, países, etc) impossibilita a existência de uma identificação única confiável que permita a remoção de itens duplicados de forma eficaz.

Para sua necessidade, o SciELO Analytics disponibiliza um conjunto de tabulações CSV que podem ser baixados para produção de indicadores.

https://analytics.scielo.org/w/reports
