### ISSUE TITLE
Traduzir toda a interface do Analytics

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/analytics#93]
@jamilatta @jfunez 

No OPAC http://homolog.opac.scielo.org/ existe um botão "Métricas" que redireciona o usuário para o site do Analytics. Se o usuário estiver usando o OPAC em EN (ou ES), ao ser redirecionado para o Analytics, ele não segue o mesmo idioma.

**Comment by fabiobatalha** [comment]
Esse direcionamento deve ser feito no link do OPAC.
