### ISSUE TITLE
One citation is missing

### ISSUE THREAD

**Issue by jlmazzei** [scieloorg/analytics#94]
Dear.

The article DOI [10.1590/S0102-695X2002000300041](http://www.scielo.br/scielo.php?pid=S0102-695X2002000300041&script=sci_arttext&tlng=es) was cited by the reference "Ion exchange chromatography applied to the fractionation of the copaíba oil (Copaifera multijuga) and sacaca (Croton cajucara) extracts" ([fourth reference in DOI: [[10.1590/S0100-40422005000400028](http://www.scielo.br/scielo.php?pid=S0100-40422005000400028&script=sci_arttext&tlng=pt).

However this citation is missing in the Scielo Analytics list of 10.1590/S0102-695X2002000300041.

Cordially

José Luiz Mazzei da Costa

**Comment by fabiobatalha** [comment]
@jlmazzei 

Infelizmente, é impossível identificar esta citação, pois a referência não faz menção ao título do artigo "Alternative extraction of alkaloid anticarcinogens from Brazilian "vinca rosea" using Ion exchange chromatography".

**Comment by jlmazzei** [comment]
Concordo com o Sr. Fábio Batalha em aprimorar a identificação de citações recebidas, uma vez que a referida citação pode ser identificada pelos nomes dos autores e periódico e pelos números dos volumes e da primeira página; esta é identificada no documento pdf.
