### ISSUE TITLE
Alterar título do gráfico de afiliação do documento

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/analytics#96]
O título do gráfico "Distribuição de países de afiliação dos documentos" deve ser alterado para "Distribuição de países de afiliação dos autores". 

![image](https://user-images.githubusercontent.com/4059679/27805983-638e18e4-600e-11e7-9f24-dbbb5af7eb4d.png)

Link: http://analytics.scielo.org/?document=S1413-92511998000200004

**Comment by fabiobatalha** [comment]
@alexxxmendonca Ajustado

![screen shot 2017-07-21 at 10 04 59](https://user-images.githubusercontent.com/504142/28464551-230cd700-6dfc-11e7-8820-ac5d9c747356.png)

**Comment by alexxxmendonca** [comment]
👍
