### ISSUE TITLE
Annali dell'Istituto Superiore di Sanità - desatualizado

### ISSUE THREAD

**Issue by ednilson** [scieloorg/analytics#97]
Este periódico está **suspenso** desde **12/06/2017** 
Esta informação está desatualizada no articlemeta e no relatório

ISSN: 0021-2571
Coleção: SPA

origem:
50  "C"
 51  "^a20100401^bC^c20170612^dS"
 62  "Istituto Superiore di Sanit�"
100  "Annali dell'Istituto Superiore di Sanit�"

**Comment by fabiobatalha** [comment]
Solucionado.
